roadmap:
  title: "My Roadmap"
  steps:
    - title: "Start here"
      start: true
    - title: "3S"
      # left: 220
    - title: "EKA design"
      # left: 440
    - title: "Alex Seif (Wp Optimize) (Social Media)"
      # top: 70
      # left: 440
    - title: "AirBnb"
      # top: 70
      # left: 220
    - title: "LDC"
      # top: 140
      # left: 220
    - title: "Finances"
      # top: 140
      left: 220
    - title: "Wuwei"
      # top: 210
      # left: 440
    - title: "EKK (Renewal)"
    - title: "Delimore"
    - title: "Renewals"
    - title: "Toqa"
      # top: 210
      # left: 440
    - title: "End here"
      end: true
      # top: 210
      # left: 220
